from tkinter import *
from tkinter import ttk
appln = Tk()
appln.title("Application for GUI to represent the University ")
Label(appln,text ="Treeview(hierarchical)").pack()
treeview = ttk.Treeview(appln)
treeview.pack()
treeview.insert('', '0', 'i1', text ='University')
treeview.insert('', '1', 'i2', text ='Computer Science')
treeview.insert('', '2', 'i3', text ='Mechanical_Engg')
treeview.insert('', 'end', 'i4', text ='Civil_Engg')
treeview.insert('', '3', 'i5' ,text="AI")
treeview.insert('i5','end',text="python")
treeview.insert('i5','end',text='data science')
treeview.insert('i2', 'end', text ='Analysis_Of_DS')
treeview.insert('i2', 'end', text ='OOPS')
treeview.insert('i3', 'end', text ='Mech_Exam')
treeview.insert('i3', 'end', text ='CAD')
treeview.insert('i4', 'end', text ='Civil_Exam')
treeview.insert('i4', 'end', text ='Drawing')
treeview.move('i2', 'i1', 'end')
treeview.move('i3', 'i1', 'end')
treeview.move('i4', 'i1', 'end')
treeview.move('i5', 'i2', 'end')
appln.mainloop()
